name: Manual Deploy
run-name: 'Manual Deploy ${{ github.event.inputs.environment }} - ${{ github.event.inputs.version }}'
concurrency: Manual Deploy ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      environment:
        description: 'Environment to deploy to'
        type: choice
        required: true
        default: 'tst'
        options:
          - 'tst'
          - 'stg'
          - 'prd'

jobs:
  deploy_start_slack:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Deploy started
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Notify deployment started
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
        payload: |
          channel: '#team-dinosaur-dev'
          text: 'Deployment of municipality-registry (${{ github.event.inputs.version }}) to ${{ github.event.inputs.environment }} has started'

  deploy_services:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [ deploy_start_slack ]
    name: Deploy
    uses: informatievlaanderen/build-pipeline/.github/workflows/deploy-v4.yml@main
    strategy:
      matrix:
        services: [
          'municipality-api',
          'municipality-import-api',
          'municipality-producer',
          'municipality-producer-snapshot-oslo',
          'municipality-projections'
        ]
    with:
      environment: ${{ github.event.inputs.environment }}
      service-name: ${{ matrix.services }}
      version: ${{ github.event.inputs.version }}
      domain: 'basisregisters'
      project: 'basisregisters'
    secrets: inherit

  deploy_finish_slack:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [ deploy_services ]
    name: Deploy finished
    runs-on: ubuntu-latest

    steps:
    - name: Notify deployment finished
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
        payload: |
          channel: '#team-dinosaur-dev'
          text: 'Deployment of municipality-registry to ${{ github.event.inputs.environment }} has finished'
